language: ruby

before_install:
  - openssl aes-256-cbc -K $encrypted_ecb526113256_key -iv $encrypted_ecb526113256_iv -in script/deploy_rsa.enc -out script/deploy_rsa -d
  - gem update --system
  - gem install bundler
  - sudo apt-get install -y lftp


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - JEKYLL_ENV=production bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ecb526113256_key -iv $encrypted_ecb526113256_iv -in script/deploy_rsa.enc -out script/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 script/deploy_key
  - echo -e "Host it34.siteground.eu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add script/deploy_key
  - ssh -i script/deploy_key -p 18765 blog1527@it34.siteground.eu ls 

deploy:
  provider: script
  skip_cleanup: true
  script: bash -x script/deploy
